### ISSUE TITLE
Voice channels can be set as farewells/greetings targets

### ISSUE THREAD

**Issue by ParadoxOrigins** [ParadoxalCorp/felix-production#33]
-Voice channels can be set as farewells/greetings targets, and perhaps as targets of other features as well, due to a mistake in the search algorithm
-If a voice channel is set, an error will occur as it wasn't planned

https://sentry.io/paradoxcorp/felix/issues/600952988/

```
Error: TypeError: channel.createMessage is not a function
    at GuildMemberRemoveHandler.handle (/applications/felix-production/events/guildMemberRemove.js:21:17)
    at process._tickCallback (internal/process/next_tick.js:178:7)
  File "/applications/felix-production/events/guildMemberRemove.js", line 21, in GuildMemberRemoveHandler.handle
    channel.createMessage(message).catch(() => {});
  File "/applications/felix-production/events/error.js", line 55, in ErrorHandler.handle
    this.sentry.captureException(err, {
  File "/applications/felix-production/main.js", line 91, in process.on
    process.on('unhandledRejection', (err) => this.bot.emit('error', err));
...
(5 additional frame(s) were not displayed)

Error: TypeError: channel.createMessage is not a function
    at GuildMemberRemoveHandler.handle (/applications/felix-production/events/guildMemberRemove.js:21:17)
    at process._tickCallback (internal/process/next_tick.js:178:7)
```

**Comment by ParadoxOrigins** [comment]
Fixed with #34
