### ISSUE TITLE
Error: Channel permission overwrite not a role nor a user ?

### ISSUE THREAD

**Issue by ParadoxOrigins** [ParadoxalCorp/felix-production#45]
https://sentry.io/paradoxcorp/felix/issues/611050341/

```
Error: { TypeError: Cannot read property 'position' of undefined
    at channelOverwrites.sort (/applications/felix-production/util/helpers/modules/Command.js:145:119)
    at Array.sort (native)
    at Command.hasChannelOverwrite (/applications/felix-production/util/helpers/modules/Command.js:145:34)
    at hasPerm (/applications/felix-production/util/helpers/modules/Command.js:102:49)
    at permissions.forEach.perm (/applications/felix-production/util/helpers/modules/Command.js:119:18)
    at Array.forEach (<anonymous>)
    at Command.clientHasPermissions (/applications/felix-production/util/helpers/modules/Command.js:118:21)
    at MessageHandler.handle (/applications/felix-production/events/messageCreate.js:32:70)
    at process._tickCallback (internal/process/next_tick.js:178:7)
  stackframes: 
   [ { file_name: '/applications/felix-production/util/helpers/modules/Command.js',
       line_number: 145 },
     { file_name: 'native array.js', line_number: 1 },
     { file_name: '/applications/felix-production/util/helpers/modules/Command.js',
       line_number: 145 },
     { file_name: '/applications/felix-production/util/helpers/modules/Command.js',
       line_number: 102 },
     { file_name: '/applications/felix-production/util/helpers/modules/Command.js',
       line_number: 119 },
     { file_name: null, line_number: null },
     { file_name: '/applications/felix-production/util/helpers/modules/Command.js',
       line_number: 118 },
     { file_name: '/applications/felix-production/events/messageCreate.js',
       line_number: 32 },
     { file_name: 'internal/process/next_tick.js', line_number: 178 } ] }
  File "/applications/felix-production/util/helpers/modules/Command.js", line 145, in channelOverwrites.sort
    return channelOverwrites.sort((a, b) => channel.guild.roles.get(b.id).position - channel.guild.roles.get(a.id).position)[0];
  File "/applications/felix-production/util/helpers/modules/Command.js", line 145, in Command.hasChannelOverwrite
    return channelOverwrites.sort((a, b) => channel.guild.roles.get(b.id).position - channel.guild.roles.get(a.id).position)[0];
  File "/applications/felix-production/util/helpers/modules/Command.js", line 102, in hasPerm
    const hasChannelOverwrite = Command.hasChannelOverwrite(channel, clientMember, perm);
  File "/applications/felix-production/util/helpers/modules/Command.js", line 119, in permissions.forEach.perm
    if (!hasPerm(perm, this)) {
  File "/applications/felix-production/util/helpers/modules/Command.js", line 118, in Command.clientHasPermissions
    permissions.forEach(perm => {
...
(12 additional frame(s) were not displayed)

Error: { TypeError: Cannot read property 'position' of undefined
    at channelOverwrites.sort (/applications/felix-production/util/helpers/modules/Command.js:145:119)
    at Array.sort (native)
    at Command.hasChannelOverwrite (/applications/felix-production/util/helpers/modules/Command.js:145:34)
    at hasPerm (/applications/felix-production/util/helpers/modules/Command.js:102:49)
    at permissions.forEach.perm (/applications/felix-production/util/helpers/modules/Command.js:119:18)
    at Array.forEach (<anonymous>)
    at Command.clientHasPermissions (/applications/felix-production/util/helpers/modules/Command.js:118:21)
    at MessageHandler.handle (/applications/felix-production/events/messageCreate.js:32:70)
    at process._tickCallback (internal/process/next_tick.js:178:7)
  stackframes: 
   [ { file_name: '/applications/felix-production/util/helpers/modules/Command.js',
       line_number: 145 },
     { file_name: 'native array.js', line_number: 1 },
     { file_name: '/applications/felix-production/util/helpers/modules/Command.js',
       line_number: 145 },
     { file_name: '/applications/felix-production/util/helpers/modules/Command.js',
       line_number: 102 },
     { file_name: '/applications/felix-production/util/helpers/modules/Command.js',
       line_number: 119 },
     { file_name: null, line_number: null },
     { file_name: '/applications/felix-production/util/helpers/modules/Command.js',
       line_number: 118 },
     { file_name: '/applications/felix-production/events/messageCreate.js',
       line_number: 32 },
     { file_name: 'internal/process/next_tick.js', line_number: 178 } ] }
```

**Comment by ParadoxOrigins** [comment]
Fixed in #46
